### ISSUE TITLE
After the upscale is completed, it is completely unlike the original picture. There are prompts in the log, which seems to be related to lcm. The diffusers have been upgraded to 0.31.0

### ISSUE THREAD

**Issue by wch352136** [smthemex/ComfyUI_InstantIR_Wrapper#4]
Comparison of original image with PMRF and instantIR
![image](https://github.com/user-attachments/assets/3c5b9603-f2fb-40ab-a5ae-bdfae86786c8)

log
`
Start infer 1 images.                                                                                                         
The config attributes {'interpolation_type': 'linear', 'skip_prk_steps': True, 'use_karras_sigmas': False} were passed to LCMSingleStepScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.    
init latent at 951                                                                                                            
finish processing                                                                                                             
Prompt executed in 81.69 seconds  
`
![image](https://github.com/user-attachments/assets/d91d8ea1-c07d-4c0b-a598-1dd4a4b2f902)

**Comment by smthemex** [comment]
你可以试着改一下底模，然后调整start和end两个参数，然后prompt加入穿着军装的人这类的限定词
You can try to change the SDXL checkpoints, adjust the start and end parameters, and then prompt to add qualifiers such as "people wearing green military uniforms"

**Comment by wch352136** [comment]
> 你可以试着改一下底模，然后调整start和end两个参数，然后prompt加入穿着军装的人这类的限定词 You can try to change the SDXL checkpoints, adjust the start and end parameters, and then prompt to add qualifiers such as "people wearing green military uniforms"

其实一开始就这么试过，没有好转，我今天看您这边的依赖有更新，我回去更新一下依赖试一试

**Comment by smthemex** [comment]
我只是更新了需求库，有些人的comfyUI库环境不匹配，没用动核心代码，比较忙，可能要晚几天才能看这个项目

**Comment by sywo84** [comment]
@wch352136  你aggregator的模型选错了

**Comment by wch352136** [comment]
> @wch352136 你aggregator的模型选错了

是的，就是这样，改工作流的时候选错了，但排查问题完全没想到这，一直找安装的问题和底模的问题，感谢感谢
