### ISSUE TITLE
"IMPORT FAILED" error

### ISSUE THREAD

**Issue by Chiaki** [smthemex/ComfyUI_InstantIR_Wrapper#5]
I've tried to install this custom node but it fails to run.

Inside of ComfyUI Node Manager I have a `(IMPORT FAILED)` next to node title. `Try Fix` button is not fixing the problem.
In console output I have this:
```
Traceback (most recent call last):
  File "X:\ComfyUI\ComfyUI\nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "X:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantIR_Wrapper\__init__.py", line 2, in <module>
    from .InstantIR_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "X:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantIR_Wrapper\InstantIR_node.py", line 9, in <module>
    from .utils import load_list_images, tensor2imglist, tensor_upscale,instantIR_main, instantIR_load_model, auto_downlaod
  File "X:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantIR_Wrapper\utils.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import X:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantIR_Wrapper module for custom nodes: No module named 'cv2'
```

ComfyUI version 0.2.7;
Os Win 11;

Manual installation and installation with custom node manager gives the same error.

**Comment by Chiaki** [comment]
Additional info:

`cv2` is a `opencv-python` module. Error was fixed by command `pip install opencv-python`.

After that I've got another error `ComfyUI_InstantIR_Wrapper module for custom nodes: No module named 'peft'`

It was fixed by `pip install peft`.

I think `requirements.txt` is not full and should contain these two modules.

**Comment by smthemex** [comment]
pip install opencv-python
you can see # in the requirements.txt

**Comment by Chiaki** [comment]
Yes. But this didn't worked with portable version of ComfyUI from official repo.
The solution was to run `python.exe -m pip install peft` and `python.exe -m pip install opencv-python` from `ComfyUI\python_embeded` folder. Then it worked.
So, it's not related to this module directly, just a difference in available ComfyUI packages.
