### ISSUE TITLE
exceptions must derive from BaseException

### ISSUE THREAD

**Issue by Amazon90** [smthemex/ComfyUI_InstantIR_Wrapper#9]
![1](https://github.com/user-attachments/assets/49320b7f-4760-4234-aa9c-dfb2a35e8be3)
# ComfyUI Error Report
## Error Details
- **Node Type:** InstantIR_Loader
- **Exception Type:** TypeError
- **Exception Message:** exceptions must derive from BaseException
## Stack Trace
```
  File "D:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\ComfyUI\custom_nodes\ComfyUI_InstantIR_Wrapper\InstantIR_node.py", line 91, in main_
    raise "need chocie a lora checkpoint"

```
## System Information
- **ComfyUI Version:** v0.2.7-13-g8a52810
- **Arguments:** D:\ComfyUI\main.py --auto-launch --preview-method auto --disable-cuda-malloc --fast
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12878086144
  - **VRAM Free:** 6538381024
  - **Torch VRAM Total:** 5033164800
  - **Torch VRAM Free:** 60278496

**Comment by smthemex** [comment]
![image](https://github.com/user-attachments/assets/b4b7db57-41c6-441e-82b8-72f02b45e484)

**Comment by Amazon90** [comment]
> ![image](https://private-user-images.githubusercontent.com/138738845/384871405-b4b7db57-41c6-441e-82b8-72f02b45e484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzA5NDMsIm5iZiI6MTczMTU3MDY0MywicGF0aCI6Ii8xMzg3Mzg4NDUvMzg0ODcxNDA1LWI0YjdkYjU3LTQxYzYtNDQxZS04MmI4LTcyZjAyYjQ1ZTQ4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQwNzUwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjk3ZGMyMDZlNjA4MTQwNDVkNDJmNzQ3Zjc2MzQ2NmUxM2Y0NTFkMDQwMGE0YmQ5MGNiYjM1OWExNjQ0ZGQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WK9LwQOhy_ntGrylTazbEq5AgsTGXJdRRCvadDRrmxc)

![1](https://github.com/user-attachments/assets/0026f1ec-3a1f-4635-9b77-9928e785ed52)
Why are the results of image generation so blurry?

**Comment by smthemex** [comment]
more step and turn off  use_clip_encoder

**Comment by Amazon90** [comment]
> more step and turn off use_clip_encoder
The result based on your suggestion is still blurry.
![2](https://github.com/user-attachments/assets/53f85ddd-517c-45df-97fb-a1e1f5e0b40e)

**Comment by Amazon90** [comment]
any SDXL checkpoint── sdxl_lightning_8step.safetensors

├── ComfyUI/models/InstantIR/models
|     ├── adapter.pt
|     ├── aggregator.pt
|     ├── previewer_lora_weights.bin
├── ComfyUI\models\InstantIR\dino
|     ├── config.json
|     ├── model.safetensors
|     ├── preprocessor_config.json
├── ComfyUI\models\loras
|     ├── lcm-lora-sdxl.safetensors

**Comment by smthemex** [comment]
yeah, it's correct. you can try add ' a man image' in prompt

**Comment by Amazon90** [comment]
> yeah, it's correct. you can try add ' a man image' in prompt

![2](https://github.com/user-attachments/assets/dafe0af2-d063-4667-b1b6-40463814a031)
Following your suggestion, but the result is still blurry. I‘m downloading SDXL base 1.0, it might be an issue with the lighting model.

**Comment by Amazon90** [comment]
![1](https://github.com/user-attachments/assets/d59b9bf8-e075-486a-9294-05e6722e123c)
![examples_input](https://github.com/user-attachments/assets/83c5bb63-6494-4dff-9671-ef80811912a6)
![ComfyUI_temp_bfnpf_00001_](https://github.com/user-attachments/assets/d75c78a1-64d1-49cb-a0d1-c7e2982d66c7)

I doubt whether it is really effective. If that's the case, it can't compare to the Flux ControlNet upscaler at all.

**Comment by smthemex** [comment]
Yes, this image restoration method does have a problem of sometimes good and sometimes bad

**Comment by Amazon90** [comment]
> Yes, this image restoration method does have a problem of sometimes good and sometimes bad

Thank you. Thank you for your efforts.
